### ISSUE TITLE
[BUG] getGamesAmerica({ shop: 'unfiltered' }) not returning all games

### ISSUE THREAD

**Issue by mmakarios** [lmmfranco/nintendo-switch-eshop#124]
**Please describe the problem you are having in as much detail as possible:**

Some games are not returning from the API using the 'unfiltered' option on getGamesAmerica, but are returning with the 'all' option. For instance: OKAMI HD, Armello, Cosmic Star Heroine.

**Include a reproducible code sample here, if possible:**
```js

getGamesAmerica({ shop: 'unfiltered' }) ...

```

**Further details:**
- version: 2.2.8
- Node.js version: v13.3.0
- Operating system: macOS Mojave 10.14.6
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Favna** [comment]
This is by design. When providing the "all" option it gets data for digital games (nintendo.com) and retail games and also only those 2. When providing the option "unfiltered" no filter at all is applied and you're leaving it entirely up to the mood of the API on what to return - which is out of our control.

**Comment by mmakarios** [comment]
So the only way to consistenly get all games is to use 'unfiltered' and 'all' and remove duplicates?

**Comment by Favna** [comment]
At this point I'm just going to release v3 with the breaking change of entirely removing the option to filter by certain shop types. It's unreliable at the best of times, hard to document and most people seem to want to just get all possible entries anyway.

That said, I am curious as to why you want all entries? That is to say, what are you intending to use this library for?

**Comment by Favna** [comment]
Published v3.0.1 which removes the option to pass a "shop" property and always returns completely unfiltered results. If `getGamesAmerica` is ever not returning a specific game that you did expect it to return then it will be on Nintendo's API side of things rather than this library.

**Comment by mmakarios** [comment]
Favna, sorry for the late reply. I wanted to get all games to build a platform where I can apply some filters to the list (price, on sale, etc). Thanks for your help.
