### ISSUE TITLE
Thoughts on converting to TypeScript?

### ISSUE THREAD

**Issue by zelein** [lmmfranco/nintendo-switch-eshop#16]
Hey,

Would there be an interest in converting this project to TypeScript? It would allow for a simplification of the jsdocs and no longer needing to maintain the separate .d.ts file since that would be auto-generated.

This would also allow for using more modern javascript styles like async/await. TypeScript could be leaned on for transpiling that code back to non-async/await code (if you're trying to support versions of node <10.) Along with other benefits of having a compiler catch errors and other things.

I'm just curious for what the general thoughts behind this would be. I work in TS for a living and would be interested in doing this. Just wanted to gauge support before I dove into it.

Cheers.

**Comment by Favna** [comment]
I can probably look into this @lmmfranco . I'll have to look into the exact workings of backporting async/await but I've been doing a lot of TypeScript projects so that part shouldn't be too hard

**Comment by zelein** [comment]
Sorry, I submitted this issue with the intention of working this but other responsibilities have risen for me.

**Comment by Favna** [comment]
Taht's alright, I'll start now. I think I'll be able to single-commit it but if not I'll push it to `favna/nintendo-switch-eshop#WIP/TypeScript-rework`

**Comment by lmmfranco** [comment]
@Favna 
>  I'll have to look into the exact workings of backporting async/await 

Check out these resources on the subject:

- https://blog.mariusschulz.com/2016/12/09/typescript-2-1-async-await-for-es3-es5
- https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library

And thanks for your help.

**Comment by Favna** [comment]
Started a bit ago, just finished setting up all the TS interfaces. And might I just say the timing is damn frigging lucky. Typings for country-data were created 3 days ago.

![image](https://user-images.githubusercontent.com/4019718/51340335-ed465b00-1a8e-11e9-93ee-8bd5c3972812.png)

**Comment by Favna** [comment]
@lmmfranco Do you have somewhere we can chat? Like Discord or something. I already have one question and bound to have more, this one being something is isn't documented but is in the code

If Discord add me: Favna#0001
