### ISSUE TITLE
[QUESTION]  Module is returning less than total NA eShop games

### ISSUE THREAD

**Issue by iRamos99** [lmmfranco/nintendo-switch-eshop#172]
Quick suggestion. I believe the reason why the "getGamesAmerica" function returns less than the actual total is that the "hitsPerPage:" attribute is set to 100. This caps the number of results per individual query. 

For example, category: "Action" and priceRange: "$0 - $4.99" has 346 results at the time of this posting. But the module only returns 100 and never creates a new request for the rest.

A quick fix is to change the "hitsPerPage" to something like 800 (that worked for me). Or allow users to set this as an option.

In my case, I'm using "priceRange" and "esrb" facets to pull all games, this creates fewer requests.

Regards,
Izay

**Comment by mmakarios** [comment]
@iRamos99, thanks for the great tip!

I can only raise "hitsPerPage" to 500, after that I start to get "Fetching of US Games failed", and still can't get all games, but it is a huge improvement from the current 100. Thank you!

**Comment by Favna** [comment]
> Or allow users to set this as an option.

This is possible, it is the first parameter of the `getGamesAmerica()` function.

`getGamesAmerica({ limit: 200 })` will only return 200 results and not paginate for example.
`getGamesAmerica({ limit: 200 }, 200)` will return results 201-400 as the second parameter is the offset. Ideally this would be merged into the object of the first parameter however that'd be a breaking change and there's no reason to make a breaking change with where the project currently stands (besides this is documented in the API docs as well, see https://lmmfranco.github.io/nintendo-switch-eshop/globals.html#getgamesamerica)
