### ISSUE TITLE
How to get sale price for Canada and other regions?

### ISSUE THREAD

**Issue by sanjsanj** [lmmfranco/nintendo-switch-eshop#19]
Hi there,

Great package, thanks for your work!

I'm trying to get the sale price for games in the Canada eStore, the only way I can see (and I'm probably wrong) is to use `.getPrices()` but when I do so I get an object like this:

```
{
  personalized: false,
  country: 'CA',
  prices:
    [ {
      title_id: 70010000004550,
      sales_status: 'onsale',
      regular_price: {
        amount: '$9.87',
        currency: 'CAD',
        raw_value: '9.87'
      }
    } ] 
```

Any idea how, or if it's even possible, to get the sale price of games not in the US/EU/JP stores?  I see in your docs there is an optional `discount_price` in the `TitleData` object but how do I get it?  Ultimately I'm just trying to figure out how to get the sale prices for other regions.

**Comment by sanjsanj** [comment]
@lmmfranco I think I've figured out I can use the ca_price and divide it by the discount % returned from the gameUS object, I've checked against some live sales and so far the number is accurate.  Is there a better way to do it though?  And this wouldn't work for other regions.

p.s. Thanks for the fast attention!

**Comment by lmmfranco** [comment]
Hi @sanjsanj 
Your code is probably correct. 
Even if most games have the `sales_status: 'onsale',` data, they are not actually on sale.
Games that are on sale when their object has the  `discount_price` key.
You can check an example of this here: [example](https://github.com/lmmfranco/nintendo-switch-eshop-examples/blob/master/nse-games-on-sale/index.js)

According to the API, only the game #KILLALLZOMBIES is on sale right now on Canada.
