### ISSUE TITLE
[QUESTION] GetGamesAmerica and games with no price

### ISSUE THREAD

**Issue by bvanzile** [lmmfranco/nintendo-switch-eshop#190]
Hi all,

I've been using the library with no issues lately and I wanted to say thank you for maintaining and sharing this repository with all of us. It's been fantastic!

Recently, I noticed some of the "Coming Soon" games from Nintendo.com weren't showing up in the final games list from a successful GetGamesAmerica call.

In the screenshot below, it can be deduced that there are 53 games in the Coming Soon category for the Nintendo Switch that have a set price and there are also 66 games that have no price set at the moment.

![image](https://user-images.githubusercontent.com/9438505/82103011-713e4080-96df-11ea-955a-ec4d4e6ede9c.png)

Looking at the code comments and a few responses in some of the other issues, I thought that this might be due to the way Price Range is used to break up the API calls (if I even understood that correctly) and possibly the intended functionality since one of the library's main intents is price/sale related, which is fair.

However, when I made a GetGamesAmerica call earlier today to test this theory, it returned 55 games with "Coming Soon" Availability instead of the expected 53. It retrieved all 53 games that are Coming Soon and have a set price. The 2 extra were games titled Fuser and Quantum League, which both returned with a null msrp, null priceRange, and no specific release date, with the Fuser output in the below screenshot.

![Screen Shot 2020-05-15 at 7 26 28 PM](https://user-images.githubusercontent.com/9438505/82104091-7b623e00-96e3-11ea-8194-e1e4c316ad73.png)

Now, I was intending to figure out a way to get all of these 66 games that are unpriced (and usually with vague release date strings) to be included in the GetGamesAmerica result array but, now that 2 of these games seem to be present in the GetGamesAmerica API response, I was wondering if someone could shed some light on the expected results. Is the intent to include all games or just those with a set price? How did these 2 unpriced games slip through without the other 64? Is there an obvious way I can modify some configurations to include games with no price and a future release date?

Thanks for taking a look!

**Comment by bvanzile** [comment]
I was able to get more game hits using the advice from the other user's question and upping the hitsPerPage limit to 500. However, this only gave me 1 more game that has no price range.

After looking a little more closely at the way the library works, I suspect these 3 games are coming through because they contain a less common category and are getting picked up in one of the pulls involving that.

I'm thinking of trying to add another Algolia call looking for games with Coming Soon availability, if it's possible. I'll leave this question up for a bit until I get around to trying that or if someone else has already resolved this and has some code to share.

**Comment by ganquan881205** [comment]
Hi @bvanzile,

I am currently creating a python-based eshop API service project. But in the process, I found some problems similar to yours. The difference is that when I use the 'availability:Available now' and 'platform:Nintendo Switch' facetFilters, found that the total number of 'nbhits' returned is not consistent with the total of all price ranges, which is about 40 different.
But I think that games which are already in 'Available now' should not return a null in priceRange.
I am very confused about this. 

So is there any solution or suggestion to this point?

![微信图片编辑_20200613042603](https://user-images.githubusercontent.com/4844617/84543503-1162a600-ad2e-11ea-9a78-0bfa35a0d938.jpg)

**Comment by Favna** [comment]
Honestly I'm not sure if there's all that much that we can do about it. If you have any suggestions then feel free to make them either through pull request or putting them in text here, but at the end of the day it's pretty much Nintendo's API that is very inconsistent with its data and we're doing the best we can with what we got.
