### ISSUE TITLE
How to get all the games and the price of the game in each country eshop

### ISSUE THREAD

**Issue by zrpgood** [lmmfranco/nintendo-switch-eshop#249]
Hi, thank you so much for developing such a great program. I plan to get all the games and their selling price in each country eshop, is this possible? I have found that the data obtained in different regions do not have a common unique id, so there is no way to merge the data, any ideas on how to do this? Very much looking forward to your reply.

**Comment by Favna** [comment]
There really isn't any good way to do this and that's purely by limitations of the Nintendo API, because like you say, they don't share unique IDs. For what it's worth, last I looked into the API we return pretty much all data it can offer.

**Comment by zrpgood** [comment]
> There really isn't any good way to do this and that's purely by limitations of the Nintendo API, because like you say, they don't share unique IDs. For what it's worth, last I looked into the API we return pretty much all data it can offer.

I've seen similar projects, I don't know how it's done, but if it can be done it means there's a way to do it, right? I recommend you check out https://eshop-prices.com/

**Comment by Favna** [comment]
Well I'm sorry but I'm not going to guide you on how to make a copy of something like eshop-prices.com, with or without this library. Such software architecture entirely on you. This lib offers the data in the way that it does, and it's up to end-users to use that data the way they want to use it.
