### ISSUE TITLE
[QUESTION] How to get data from eshop in Hong Kong

### ISSUE THREAD

**Issue by zrpgood** [lmmfranco/nintendo-switch-eshop#254]
How to get data from eshop in Hong Kong?Checked the API documentation and found none.

**Comment by Favna** [comment]
We do not support the Hong Kong eShop at the moment. If you know how to request data from their store you are free to create a pull request for it.

**Comment by Peter-Huang0623** [comment]
> How to get data from eshop in Hong Kong?Checked the API documentation and found none.

https://www.nintendo.com.hk/data/json/switch_software.json

this is what you need
