### ISSUE TITLE
 How to know the API url

### ISSUE THREAD

**Issue by liseen315** [lmmfranco/nintendo-switch-eshop#27]
Hello, I saw that there are API urls for each region in the code. How do I get the request on which page of the official website? Thank you.

**Comment by liseen315** [comment]
like http://www.nintendo.com/json/content/get/filter/game this url where was it found?

**Comment by lmmfranco** [comment]
To find them I visited each region website and checked the game search page. (like this one https://www.nintendo.com/games/game-guide?pv=true#filter/switch|-|-|-|-|-|-|-|-|-|-|-|-|-|||-|-|-), from here just open your browser's network tab and check the requests, you should find the url you mentioned.
As for pricing info, check network info when opening a game detail page.
