### ISSUE TITLE
GET_GAMES_US_URL:  No Longer Valid

### ISSUE THREAD

**Issue by iRamos99** [lmmfranco/nintendo-switch-eshop#37]
The GET_GAMES_US_URL is no longer valid. Do you all know if there is a new endpoint to the US eshop json api?

The GET_GAMES_EU_URL is still valid!

**Comment by lmmfranco** [comment]
It seems nintendo is now using a third party service for their searches.
This will probably make our life way harder -.-"

```
curl 'https://u3b6gr4ua3-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.22.1%3BJS%20Helper%202.20.1&x-algolia-application-id=U3B6GR4UA3&x-algolia-api-key=9a20c93440cf63cf1a7008d75f7438bf' -H 'accept: application/json' -H 'Referer: https://www.nintendo.com/games/game-guide/' -H 'Origin: https://www.nintendo.com' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' --data '{"requests":[{"indexName":"noa_aem_game_en_us","params":"query=&hitsPerPage=42&maxValuesPerFacet=30&page=0&facets=%5B%22generalFilters%22%2C%22platform%22%2C%22availability%22%2C%22categories%22%2C%22filterShops%22%2C%22virtualConsole%22%2C%22characters%22%2C%22priceRange%22%2C%22esrb%22%2C%22filterPlayers%22%5D&tagFilters=&facetFilters=%5B%5B%22filterShops%3AOn%20Nintendo.com%22%5D%2C%5B%22platform%3ANintendo%20Switch%22%5D%5D"},{"indexName":"noa_aem_game_en_us","params":"query=&hitsPerPage=1&maxValuesPerFacet=30&page=0&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&facets=filterShops&facetFilters=%5B%5B%22platform%3ANintendo%20Switch%22%5D%5D"},{"indexName":"noa_aem_game_en_us","params":"query=&hitsPerPage=1&maxValuesPerFacet=30&page=0&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&facets=platform&facetFilters=%5B%5B%22filterShops%3AOn%20Nintendo.com%22%5D%5D"}]}' --compressed
```

**Comment by chevol** [comment]
Yup, been struggling with this myself. Strange that they also allow their Algolia api-key and application id to be visible like that. Technically we could just call to Algolia too, but I'm sure Nintendo will change that and lock it down better soon.

**Comment by chevol** [comment]
Yup, been struggling with this myself. Strange that they also allow their Algolia api-key and application id to be visible like that. Technically we could just call to Algolia too, but I'm sure Nintendo will change that and lock it down better soon.

**Comment by chevol** [comment]
Yup, been struggling with this myself. Strange that they also allow their Algolia api-key and application id to be visible like that. Technically we could just call to Algolia too, but I'm sure Nintendo will change that and lock it down better soon.

**Comment by chevol** [comment]
Yup, been struggling with this myself. Strange that they also allow their Algolia api-key and application id to be visible like that. Technically we could just call to Algolia too, but I'm sure Nintendo will change that and lock it down better soon.

**Comment by iRamos99** [comment]
Here are some samples of the search and data model. 

**Sample search page**
`<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.css">
        <script src="https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js"></script>
    </head>

    <body>
        <style>
            .ais-hits--item {
                display: inline-block;
                border: 1px solid #333;
                padding: 10px;
                margin: 10px 0 0 10px;
                text-align: center;
            }
            .art img {
                display: block;
                margin-left: 10px;
                width: 60px;
            }
        </style>

        <input type="text" id="search-box" class="form-control"/>
        <div id="hits-container"></div>
        <div id="pagination-container"></div>

        <script>
            var search = instantsearch({
                appId: 'U3B6GR4UA3',
                apiKey: '9a20c93440cf63cf1a7008d75f7438bf',
                indexName: 'noa_aem_game_en_us_title_asc',
                urlSync: { useHash: true }
            });
            search.addWidget(
                instantsearch.widgets.searchBox({
                    container: '#search-box',
                    autofocus: true,
                    placeholder: 'What?'
                })
            );
            search.addWidget(
                instantsearch.widgets.hits({
                    container: '#hits-container',
                    templates: {
                        empty: 'No Results',
                        item: '<div class="item"><div class="title"><label>{{title}}</label></div><div class="art"><img src="http://www.nintendo.com{{boxArt}}"/></div></div>'
                    }
                })
            );
            search.addWidget(
                instantsearch.widgets.pagination({
                    container: '#pagination-container'
                })
            );
            search.start();
        </script>
    </body>
</html>`

**Search Result JSON for a single item**
`{
  "type": "game",
  "locale": "en_US",
  "url": "/games/detail/breakforcist-battle-switch",
  "title": "#Breakforcist Battle",
  "description": "Are you hungry!? Introducing an all new version of the cult favorite \n      breakfast/exorcism-themed waffle-busting game, #Breakforcist Battle! Use \n      your magic paddle & ball to rescue breakfast with classic brick-breaking \n      gameplay. Work together with a friend in cooperative play or challenge \n      your friends in an all new competitive battle mode!\n    \n    \n      A collaboration between Lucid Sheep Games & visual artist Pete Ellison.\n    \n    \n      FEATURES:\n    \n    \n      \n        An endless twist on classic brick-breaking gameplay, complete with \n        crazy powerups!\n      \n      \n        Experience competitive brick-breaking in Battle Mode with up to 4 \n        players! Clear waves quickly to win rounds while launching all-new \n        attack powerups at your foes!\n      \n      \n        The original arcade-style game in solo play - try to survive endless \n        waves of waffles and get a high score!\n      \n      \n        Work together in 2-player cooperative mode! You share one playfield \n        but can only move on your half - you’ll need teamwork to get a high \n        score!\n      \n      \n        Bacon lasers!\n      \n      \n        An all original EDM soundtrack featuring songs like "WAFFLE♡LOVE" and \n        "Brunch My Body"\n      \n      \n        You want characters? There's 8 of them!\n      \n      \n        Giant pancakes, that may or may not be flammable.\n      \n      \n        One-handed gameplay; get a high score while eating your breakfast!\n      \n      \n        Experience 0-button gameplay with the tilt control option.\n      \n      \n        Seriously, the soundtrack is really, really good.",
  "lastModified": 1554852865971,
  "id": "oNfMa9bCbSistTheDdqCtqZ3Lwk_WBw8",
  "nsuid": "70010000003782",
  "slug": "breakforcist-battle-switch",
  "boxArt": "/content/dam/noa/en_US/games/switch/b/breakforcist-battle-switch/Switch_BreakforcistBattle_box_eShop.png",
  "gallery": "/content/dam/noa/en_US/games/switch/b/breakforcist-battle-switch/screenshot-gallery/Switch_BreakforcistBattle_01.jpg",
  "platform": "Nintendo Switch",
  "releaseDateMask": "2018-04-12T00:00:00.000Z",
  "characters": [],
  "categories": [
    "Arcade",
    "Multiplayer",
    "Party",
    "Puzzles"
  ],
  "msrp": 9.99,
  "esrb": "Everyone",
  "esrbDescriptors": [],
  "virtualConsole": "na",
  "generalFilters": [],
  "filterShops": [
    "On Nintendo.com"
  ],
  "filterPlayers": [
    "3+",
    "2+",
    "1+"
  ],
  "players": "up to 4 players",
  "featured": false,
  "freeToStart": false,
  "priceRange": "$5 - $9.99",
  "salePrice": null,
  "availability": [
    "Available now"
  ],
  "objectID": "a4448394-71c9-3998-8e08-09ae9b01507b",
  "_highlightResult": {
    "type": {
      "value": "game",
      "matchLevel": "none",
      "matchedWords": []
    },
    "locale": {
      "value": "en_US",
      "matchLevel": "none",
      "matchedWords": []
    },
    "url": {
      "value": "/games/detail/breakforcist-battle-switch",
      "matchLevel": "none",
      "matchedWords": []
    },
    "title": {
      "value": "#Breakforcist Battle",
      "matchLevel": "none",
      "matchedWords": []
    },
    "description": {
      "value": "Are you hungry!? Introducing an all new version of the cult favorite \n      breakfast/exorcism-themed waffle-busting game, #Breakforcist Battle! Use \n      your magic paddle & ball to rescue breakfast with classic brick-breaking \n      gameplay. Work together with a friend in cooperative play or challenge \n      your friends in an all new competitive battle mode!\n    \n    \n      A collaboration between Lucid Sheep Games & visual artist Pete Ellison.\n    \n    \n      FEATURES:\n    \n    \n      \n        An endless twist on classic brick-breaking gameplay, complete with \n        crazy powerups!\n      \n      \n        Experience competitive brick-breaking in Battle Mode with up to 4 \n        players! Clear waves quickly to win rounds while launching all-new \n        attack powerups at your foes!\n      \n      \n        The original arcade-style game in solo play - try to survive endless \n        waves of waffles and get a high score!\n      \n      \n        Work together in 2-player cooperative mode! You share one playfield \n        but can only move on your half - you’ll need teamwork to get a high \n        score!\n      \n      \n        Bacon lasers!\n      \n      \n        An all original EDM soundtrack featuring songs like "WAFFLE♡LOVE" and \n        "Brunch My Body"\n      \n      \n        You want characters? There's 8 of them!\n      \n      \n        Giant pancakes, that may or may not be flammable.\n      \n      \n        One-handed gameplay; get a high score while eating your breakfast!\n      \n      \n        Experience 0-button gameplay with the tilt control option.\n      \n      \n        Seriously, the soundtrack is really, really good.",
      "matchLevel": "none",
      "matchedWords": []
    },
    "lastModified": {
      "value": "1554852865971",
      "matchLevel": "none",
      "matchedWords": []
    },
    "id": {
      "value": "oNfMa9bCbSistTheDdqCtqZ3Lwk_WBw8",
      "matchLevel": "none",
      "matchedWords": []
    },
    "nsuid": {
      "value": "70010000003782",
      "matchLevel": "none",
      "matchedWords": []
    },
    "slug": {
      "value": "breakforcist-battle-switch",
      "matchLevel": "none",
      "matchedWords": []
    },
    "boxArt": {
      "value": "/content/dam/noa/en_US/games/switch/b/breakforcist-battle-switch/Switch_BreakforcistBattle_box_eShop.png",
      "matchLevel": "none",
      "matchedWords": []
    },
    "gallery": {
      "value": "/content/dam/noa/en_US/games/switch/b/breakforcist-battle-switch/screenshot-gallery/Switch_BreakforcistBattle_01.jpg",
      "matchLevel": "none",
      "matchedWords": []
    },
    "platform": {
      "value": "Nintendo Switch",
      "matchLevel": "none",
      "matchedWords": []
    },
    "releaseDateMask": {
      "value": "2018-04-12T00:00:00.000Z",
      "matchLevel": "none",
      "matchedWords": []
    },
    "categories": [
      {
        "value": "Arcade",
        "matchLevel": "none",
        "matchedWords": []
      },
      {
        "value": "Multiplayer",
        "matchLevel": "none",
        "matchedWords": []
      },
      {
        "value": "Party",
        "matchLevel": "none",
        "matchedWords": []
      },
      {
        "value": "Puzzles",
        "matchLevel": "none",
        "matchedWords": []
      }
    ],
    "msrp": {
      "value": "9.99",
      "matchLevel": "none",
      "matchedWords": []
    },
    "esrb": {
      "value": "Everyone",
      "matchLevel": "none",
      "matchedWords": []
    },
    "virtualConsole": {
      "value": "na",
      "matchLevel": "none",
      "matchedWords": []
    },
    "filterShops": [
      {
        "value": "On Nintendo.com",
        "matchLevel": "none",
        "matchedWords": []
      }
    ],
    "filterPlayers": [
      {
        "value": "3+",
        "matchLevel": "none",
        "matchedWords": []
      },
      {
        "value": "2+",
        "matchLevel": "none",
        "matchedWords": []
      },
      {
        "value": "1+",
        "matchLevel": "none",
        "matchedWords": []
      }
    ],
    "players": {
      "value": "up to 4 players",
      "matchLevel": "none",
      "matchedWords": []
    },
    "priceRange": {
      "value": "$5 - $9.99",
      "matchLevel": "none",
      "matchedWords": []
    },
    "availability": [
      {
        "value": "Available now",
        "matchLevel": "none",
        "matchedWords": []
      }
    ]
  },
  "__hitIndex": 0
}`

**Comment by Favna** [comment]
It should be noted that Algolia uses Search-Only keys and the key that is in the URL should be perfectly fine to use. Further info about this can be found on the [Algolia Documenation](https://www.algolia.com/doc/guides/security/api-keys/) but suffice it to say that the key *should* be public.

I created a [Postman](https://www.getpostman.com/) collection with a sample using @lmmfranco's CURL request, you can view it [here](https://www.getpostman.com/collections/d573f2f9c352dfdb3833)

**Comment by pompeywebb** [comment]
Querying for the data is pretty straight forward. My two major annoyances:

1. Only 1000 results will ever be returned for a given index, meaning if you want all 2000+ title then you need to query multiple indexes, and indeed query with a search for each alphabet letter from my experiments.

2. The search API does not return the game code. I've asked for all facets to be returned, and none of them seem to contain it. Currently they can be retrieved from each individual game page (it's part of an object defined in the HTML), but this requires an extra 2000+ requests to get a complete data set.

At least demo/dlc/nintendo online requirements are still part of the API results.

**Comment by ivanxpru** [comment]
I get only 914 results. How to get more? I try to change the page parameter in URL, but it's not working.

**Comment by Alex-Lema** [comment]
And the API does not return the product code anymore? With that, there's no way to find differences between areas, right?

**Comment by ivanxpru** [comment]
I find the problem in query: &facetFilters=[["filterShops:On Nintendo.com,"]]. It is returned only 914 games. But if add "At retail", then get +280 games. But I don't recognize how to add this parameter to query for cURL.

**Comment by pompeywebb** [comment]
> I find the problem in query: &facetFilters=[["filterShops:On Nintendo.com,"]]. It is returned only 914 games. But if remove ["filterShops:On Nintendo.com,"], then can get 1000 games. But I don't recognize how to get more items. I try chamge page parameter, but it does not work.

You need to query for multiple indexes to get a complete set of available assets. In fact, multiple queries, each with a different alphabet letter search term, is required to build the entire list.

I'm not at all familiar with the capabilities of the Aloglia functionality, but if it supports regex then multiple queries on the same index, each with a 'starts with (a-z)' search term, should be enough to return all assets. I'm pretty sure there are not >1000 assets that start with the same letter (at the moment). I want to test this but haven't had the time to refactor and simplify after I got it all working a little while ago.

**Comment by iRamos99** [comment]
This is what I'm doing as an attempt to get the full list. This is very inefficient and returns all kinds of duplicates. So, need to dedupe the results. I'm doing upserts to my database, so, it isn't a big deal for now. Also, I haven't verified that in fact I'm getting the full list. I have 2,162 items in my db.

`var indexes = ["noa_aem_game_en_us_price_des", "noa_aem_game_en_us_price_asc", "noa_aem_game_en_us_title_des", "noa_aem_game_en_us_title_asc", "noa_aem_game_en_us_release_des"];
function doSearch(i, hits, callback) {
    var client = algoliasearch('U3B6GR4UA3', '9a20c93440cf63cf1a7008d75f7438bf');
    var index = client.initIndex(indexes[i]);
    var hits = hits || [];
    var nextIndex = i + 1;
    var searcher = index.search({
        query: "",
        offset: 0,
        length: 1000,
        filters:'platform:"Nintendo Switch"'
    }, function (err, content) {
        if (err) {
            console.log('Error:' + err);
            callback('[[ERROR]] ' + err);
        }
        if (nextIndex >= indexes.length) {
            hits = hits.concat(content.hits);
            callback(hits);
        } else if (nextIndex < indexes.length) {
            hits = hits.concat(content.hits);
            hits = doSearch(nextIndex, hits, callback);
        } else {
            callback(hits);
        }
    });
}

function getAllGamesNA() {
    return new Promise(function (resolve, reject) {
        doSearch(0, null, function (result) {
            if (result.indexOf('[[ERROR]]') != -1) {
                console.log(result);
                reject(result);
            } else {
                //console.log(JSON.stringify(result,null,2));
                resolve(result);
            }
        });
    });
}`

**Comment by Favna** [comment]
To you guys trying to find a solution to the issue, please note that PRs are more than welcome. Just be aware that I (can't really speak for Franco) will be strict on things like code quality / style (I.e. abide by the linter and try to follow pre-existing code style) and especially proper typings (no skimping out with `any` unless absolutely necessary since `any` is going against the very reason to use TypeScript)

**Comment by Favna** [comment]
That said I'm also the kind of person who'd take your code and make the necessary stlylistic changes myself. I won't only critique.

**Comment by reinvanimschoot** [comment]
Has anyone found a solid solution to this problem?

**Comment by Favna** [comment]
Aside from querying single games by querying the Algolia search not really @reinvanimschoot. This however is enough for my needs as I use it for a Discord bot. This is the query made. `query` is the name of the parameter that holds the game's name to find. the NINTENDO_ALGOLIA_ID and NINTENDO_ALGOLIA_KEY can be inferred from the Franco's URL in the first comment.

```js
await fetch(
                `https://${process.env.NINTENDO_ALGOLIA_ID}-dsn.algolia.net/1/indexes/*/queries`,
                {
                    body: JSON.stringify(
                        {
                            requests: [
                                {
                                    indexName: 'noa_aem_game_en_us',
                                    params: stringify({
                                        facetFilters: [
                                            ['filterShops:On Nintendo.com'],
                                            ['platform:Nintendo Switch']
                                        ],
                                        facets: [
                                            'generalFilters', 'platform', 'availability', 'categories',
                                            'filterShops', 'virtualConsole', 'characters', 'priceRange',
                                            'esrb', 'filterPlayers'
                                        ],
                                        hitsPerPage: 42,
                                        maxValuesPerFacet: 30,
                                        page: 0,
                                        query,
                                    }),
                                }
                            ],
                        }
                    ),
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Algolia-API-Key': process.env.NINTENDO_ALOGLIA_KEY!,
                        'X-Algolia-Application-Id': process.env.NINTENDO_ALGOLIA_ID!,
                    },
                    method: 'POST',
                }
            );
```

**Comment by reinvanimschoot** [comment]
Thanks @Favna ! I guess I'll have to do without the American games then for now. I guess it is probable that they will do the same with the European shop as well? Or am I mistaken? 

Btw, if you make use of the Algolia search package, would it not be possible to use some sort of pagination to get all the games? So not really making use of a crawler I guess, but just searching the games list itself.

**Comment by Favna** [comment]
@reinvanimschoot I'm not using the "Algolia search package". I send a manual HTTP POST with node-fetch. Since Algolia is a blazingly fast API I have not lost any speed as opposed to the method I used in the past where I cached all data and refreshed that periodically.

The code as shared earlier by IRamos99 would in fact return multiple results however far from a full set of them.

As for whether they'll do this to Europe as well, I'm not sure. Maybe they will, maybe they won't. However Europe was missing information that I would like to display in my bot so I couldn't use it, to give an idea this is what I return:

![image](https://user-images.githubusercontent.com/4019718/59967630-18951080-952d-11e9-9791-b34cfff6ded2.png)


As an aside what I do like about the move to Algolia is that it's no longer limited to Switch games, barring such a filter is not given in the POST request body. For example I can find 3DS titles:
![image](https://user-images.githubusercontent.com/4019718/59967642-4e39f980-952d-11e9-9659-2da3f4183426.png)

**Comment by iRamos99** [comment]
@reinvanimschoot I think that given the number of games currently on the Switch the code that I shared previously should get you a full list of games. I'm currently using both, the EU and Algolia database to update my local database. My project is in node.js, l can share my code if you want it. 

Also, my search database is exposed via endpoint "https://www.nsgreviews.com/search/s?search=&limit=5000"

project site: https://www.nsgreviews.com

**Comment by reinvanimschoot** [comment]
@iRamos99 That would be super helpful! Maybe you can email me at reinvanimschoot@gmail.com since I guess we shouldn't use this issue to discuss this. I would also be very interested to know at what intervals you update your database then? I have always tried to get a unified game list for both EU and US, not sure how you approach that. In any case, thanks for the help!

**Comment by solarhell** [comment]
Any progress？

**Comment by frozenzj** [comment]
If you want to crawl all games' info on the Algolia ,I suggest query for each alphabet letter as @pompeywebb 's suggestion.
here is the python script with Algolia offical API Client

```
import string
from algoliasearch.search_client import SearchClient
client=SearchClient.create('U3B6GR4UA3','9a20c93440cf63cf1a7008d75f7438bf')
index=client.init_index("noa_aem_game_en_us")
a2z=string.ascii_lowercase

for a in a2z:
    s=index.search('/content/dam/noa/en_US/games/switch/{}'.format(a),
            {
                'page': 0,
                'hitsPerPage': 1000,
                'maxValuesPerFacet':30,
                'facetFilters':[
                    ["availability:Available now"
                    ],
                    ['platform:Nintendo Switch'],
                ],
            },
                  )
```
The 'Available now' status games' info all I get are up to 11k.
