### ISSUE TITLE
[QUESTION] Moving Out game is not being fetched in getGamesAmerica

### ISSUE THREAD

**Issue by maysaleba** [lmmfranco/nintendo-switch-eshop#452]
Hi,

First off thank you for this amazing script! I've been using this to fetch games in US but for some reason today this game
https://www.nintendo.com/games/detail/moving-out-switch/ is not being fetched.

**Comment by Favna** [comment]
Hi there, if the game really is not there then that's an API limitation that this library can't solve. The game can be found with `getQueriedGamesAmerica`, which is a more stable and recommended solution to get games, with the big difference being that you won't get _all_ games, but only some games.

**Comment by Favna** [comment]
Closing this because stale

**Comment by maysaleba** [comment]
Hi, sorry for this really late response, but the reason i'm using getGamesAmerica is to get all games that are currently on sale. I'm not sure if getQueriedGamesAmerica would be able to achieve that?

**Comment by Favna** [comment]
It wouldn't achieve that. So then all I can say is that the lib can't improve on it. We're restricted by what Nintendo's API gives us.
