### ISSUE TITLE
Does getGamesAmerica returns unreleased games?

### ISSUE THREAD

**Issue by Iseiju** [lmmfranco/nintendo-switch-eshop#47]
Hi everyone, I'm trying to get a list of nintendo switch games on sale but the count is different from mine and from nintendo's website. Not sure if this is related to the paging or if the function only returns released games.

Nintendo
![image](https://user-images.githubusercontent.com/32929155/63142425-4e7ddf00-c01c-11e9-98ba-70d1d89cfab0.png)

Mine (filtered by salePrice != null && platform = 'Nintendo Switch')
![image](https://user-images.githubusercontent.com/32929155/63142465-7bca8d00-c01c-11e9-9d17-f4ad38755f66.png)

Thanks in advance!

**Comment by Favna** [comment]
What exactly is this 125? The `getGamesAmerica` should return 2486 hits at time of writing when adding `shop: 'unfiltered'`:

```js
let data = await getGamesAmerica({shop: 'unfiltered'})

// Did this in between just so I didnt have to keep querying algolia
fs.writeFileSync(path.join(__dirname, 'games.json'), JSON.stringify(data), { encoding: 'utf8' });
// and read it again
let games = fs.readFileSync(path.join(__dirname, 'games.json'), { encoding: 'utf8' });
games = JSON.parse(games);

console.log(games.length) // 2486

const botw = games.filter(game => game.title.toLowerCase().includes('breath of the wild'));
console.log(botw); // breath of the wild data
```

**Comment by Iseiju** [comment]
Hi Fanva, the 125 is filtered by nintendo switch games that are currently on sale.

Here's a screenshot of that code.
![image](https://user-images.githubusercontent.com/32929155/63228092-14315f00-c221-11e9-81c7-1f54de18fbf3.png)

At the time of this writing, I logged **result.length** to get the total list of unfiltered games and the result was 1017. After running through the filter condition, the total count would then be 116.

**Comment by Iseiju** [comment]
Hi Fanva, the 125 is filtered by nintendo switch games that are currently on sale. Here's the code that I'm using

```
getGamesAmerica().then((result) => {
        console.log(result.length)
        result.forEach((element) => {
            if (element.salePrice != null && element.platform == 'Nintendo Switch') {
                let company = element.developers == null ? element.publishers : element.developers
                var game = {
                    id: id,
                    url: url + element.url,
                    title: element.title,
                    description: element.description,
                    boxArt: url + element.boxArt,
                    releaseDate: element.releaseDateMask,
                    categories: element.categories,
                    esrb: element.esrb,
                    company: company,
                    availability: element.availability,
                    price: element.msrp,
                    salePrice: element.salePrice
                }
                array.push(game)
                id = id + 1
            }
        });

        let dataEnvelope = {}
        dataEnvelope.data = array

        res.send(dataEnvelope)
    }).catch((error) => {
        console.log(error)
        res.sendStatus(400)
    })
```

At the time of this writing, I logged **result.length** to get the total list of unfiltered games and the result was 1017. After running through the filter condition, the total count would then be 116.

**Comment by Favna** [comment]
Ah. Well to answer your question, yes Algolia does return unreleased games. Did a quick check by trying to find Pokemon Sword with my Discord bot which implements the code:

![image](https://user-images.githubusercontent.com/4019718/63229216-77f66080-c1fe-11e9-81a3-b017e3ff61e0.png)


It also returns special editions:
![image](https://user-images.githubusercontent.com/4019718/63229228-8c3a5d80-c1fe-11e9-8200-010a99d10317.png)

**Comment by Iseiju** [comment]
Alright! thanks @Favna
