### ISSUE TITLE
[BUG] Mario Kart missing from American Games query

### ISSUE THREAD

**Issue by jmsunseri** [lmmfranco/nintendo-switch-eshop#473]
**Please describe the problem you are having in as much detail as possible:**

I don't know whose problem this is but it seems like Mario Kart is missing from the API.  It's available on the nintendo website so i had assumed it would be available via their API.  Is something odd with the query you are passing to their API to exclude Mario Kart.  

https://www.nintendo.com/games/detail/mario-kart-8-deluxe-switch/

**Comment by Favna** [comment]
Hm.. you're right.

![image](https://user-images.githubusercontent.com/4019718/122657583-2950df00-d165-11eb-8afc-61f23ea93206.png)

**Comment by Favna** [comment]
Published [v6.0.1](https://github.com/lmmfranco/nintendo-switch-eshop/releases/tag/v6.0.1) which fixes this issue by specifically requesting some common franchises (Zelda, Mario, Pokémon and Kirby)

**Comment by jmsunseri** [comment]
you are amazing
