### ISSUE TITLE
Getting VideoURL and VideoThumbnailURL

### ISSUE THREAD

**Issue by jcaracciolo** [lmmfranco/nintendo-switch-eshop#5]
I've noticed there is a video_link in the USGames object. Doing a little research i found out that is only and ID and the corresponding URL are given by

```
thumbnailURL = http://cf.c.ooyala.com/{video_link}/PE3O6Z9ojHeNSk7H4xMDoxOjA1O37pTB
videoURL = http://cf.c.ooyala.com/{video_link}/DOcJ-FxaFrRg4gtDEwOjFmZzowczE7F2
```
I dont have setup anything to make a PR so if you want to go ahead, or just leave it here for future developers to find it out

**Comment by ValKiriann** [comment]
I will do it :-)

**Comment by Favna** [comment]
@jcaracciolo well this is an extremely late reply if any exists but can you elaborate? Specifically where do you get the `PE3O6Z9ojHeNSk7H4xMDoxOjA1O37pTB` and `DOcJ-FxaFrRg4gtDEwOjFmZzowczE7F2` from? The data returned by the lib for a game such as 1-2-Switch is as follows and I can't tell from your reply what goes where unless you're saying more info should be gotten from somewhere:

```ts
    const game: GameUS = {
        buyitnow: true,
        buyonline: true,
        ca_price: 64.99,
        categories: {category: ['Party', 'Multiplayer', 'Action'],},
        digitaldownload: false,
        eshop_price: 49.99,
        free_to_start: false,
        front_box_art: 'https://media.nintendo.com/nintendo/bin/oiM2QlLg9frNJhSWvFGmi5NAvEAGlYVx/_3d_ldcR3G0YQl590uHXZ89Jmouu5aS9.png',
        game_code: 'HACPAACCA',
        id: 'QY7EtPDIW1WGVWSEkQ7ZVLvCFvonU-Wl',
        nsuid: '70010000000141',
        number_of_players: '2 players simultaneous',
        release_date: 'Mar 3, 2017',
        slug: '1-2-switch',
        system: 'Nintendo Switch',
        title: '1-2-Switch',
        video_link: 'h1OTBqODE64B-g16PJeQj6tifbVKl_v8',
    };
```

**Comment by Favna** [comment]
Closing because issue is stale. If new information is available it can be re-opened
