### ISSUE TITLE
[QUESTION] What's the usage restrictions (if any) on the API this package calls?

### ISSUE THREAD

**Issue by ahungry** [lmmfranco/nintendo-switch-eshop#505]
Is there a limit to http calls?  Is this allowed by Nintendo?

What if I want to make a web based page that provides a more usable/searchable eshop experience, and I'm caching results on the server - would there be any issue you could see with that from the Nintendo POV?

**Comment by Favna** [comment]
Unknown. You'll have to handle your own rate limiting and caching as you see it required. It is always recommended with external APIs like this to build your architecture in such a way that every request will consider a cache, i.e. using something like Redis.

**Comment by ahungry** [comment]
Does Nintendo publish this API (I couldn't find any documents on it's usage at all) or is this just reverse engineering of their own web based API endpoints (such as their front end being a SPA, and needing to call these endpoints to get data)?

**Comment by Favna** [comment]
Reverse engineered. Nintendo would never publish the API lol.. it's Nintendo.

**Comment by Favna** [comment]
Closing because stale
