### ISSUE TITLE
[QUESTION] Can I use this with python?

### ISSUE THREAD

**Issue by thisisaguy** [lmmfranco/nintendo-switch-eshop#52]
Can use this with python and if yes how can I use it?
Sorry I'm really new at this.

**Comment by lmmfranco** [comment]
No. You must use node.js for this library to be useful.
If you really want to use this anyway, you could write a node.js script to generate a json file and load it later on your python script.
If you feel like making a python wrapper from scratch you could look at the source code for this lib and use as reference to know which URLs and parameters for your requests.

**Comment by thisisaguy** [comment]
Thanks
