### ISSUE TITLE
[QUESTION] Australian and NZ stores

### ISSUE THREAD

**Issue by AdrienEtienne** [lmmfranco/nintendo-switch-eshop#55]
Is it possible to get the games for these stores using the library?

**Comment by Favna** [comment]
Currently that's not possible. This library only implements the USA (through Algolia), European and Japanese(/Asian) eShops. If you know how to query the eshop for Oceania then by all means either share the code of even more preferably, implement the code and create a pull-request.

**Comment by AdrienEtienne** [comment]
Thx for your answer.
I didn't find any endpoints available for Australia/NZ games. The websites are rendered on the server side...

I can get prices using the `getPrices` method using ID from the European eshop, which is find for me.
For example `getPrices('AU', '70010000000733')` will get you the price of Yoshi in Australia.
But all the games available in Europe are not necessarily available in AU/NZ.
So maybe the method `getGamesEurope` should be called `getGamesEuropeAndPotentiallyAUAndNZ` :).

**Comment by Favna** [comment]
I'll add some documentation to the function to mention that it does also support AU / NZ in the upcoming commit and close the issue when it's available.

**Comment by AdrienEtienne** [comment]
Great!
