### ISSUE TITLE
[QUESTION] eshop update time

### ISSUE THREAD

**Issue by TheVinhLuong** [lmmfranco/nintendo-switch-eshop#58]
Hi, nice lib you have here, thanks for your hard work. 
Is there a fixed time when Nintendo update the eShop's content like discount and new games? If yes then does it vary between regions?

**Comment by Favna** [comment]
As far as I know there is no fixed time and even if a pattern could be distinguished then it will vary by region as every regions is managed by their own subsidiary and manages their own discounts. This lib is also not concerned with such things. The lib simply queries the Nintendo API regardless of what that API returns.

**Comment by TheVinhLuong** [comment]
Thanks for your answer. I know that this lib query Nintendo API directly but I want to reduce the number of times I make a direct query by caching the result for as long as eshop's data (of specific region) doesn't change. I guess I will need to find another approach then.

**Comment by Favna** [comment]
If that closes the question I'll close the issue. Feel free to re-open if you have further questions.
