### ISSUE TITLE
[BUG] Cannot run tests

### ISSUE THREAD

**Issue by mmakarios** [lmmfranco/nintendo-switch-eshop#61]
**Please describe the problem you are having in as much detail as possible:**

After a clean configuration of the repository following the instructions in the [contribution guideline](https://github.com/lmmfranco/nintendo-switch-eshop/blob/master/.github/CONTRIBUTING.md), I am unable to run the automated tests. After running `yarn lint && yarn test`, the terminal stops at `nintendo-switch-eshop: $ jest` and nothing happens, even if I make changes to the files.

**Include a reproducible code sample here, if possible:**

Terminal sample:
```zsh

 nintendo-switch-eshop ➤ yarn lint && yarn test

yarn run v1.19.1
$ lerna run lint --parallel
lerna notice cli v3.16.4
lerna info Executing command in 1 package: "yarn run lint"
nintendo-switch-eshop: $ eslint src __tests__ --ext js,ts --fix
lerna success run Ran npm script 'lint' in 1 package in 4.3s:
lerna success - nintendo-switch-eshop
✨  Done in 6.41s.
yarn run v1.19.1
$ lerna run test --parallel
lerna notice cli v3.16.4
lerna info Executing command in 1 package: "yarn run test"
nintendo-switch-eshop: $ jest

```

**Further details:**
- version: 2.2.3
- Node.js version: 12.11.1
- Operating system: macOS 10.14.6
- Priority this issue should have – please be realistic and elaborate if possible: High

- [x] I have also tested the issue on latest master, commit hash: 9405bb389fb2bbcb92e8c9ba96f1a5363b676c7a

**Comment by lmmfranco** [comment]
Since our code relies on nintendo's undocumented API we gotta fire actual HTTP requests during tests which is subject to network speed and rate limiting. It is expected that the tests take several minutes running before any information is printed on console, and that is most likely what happened there.
Thanks for you report and the pull request you submitted.
