### ISSUE TITLE
[QUESTION] 404 while opening documentation

### ISSUE THREAD

**Issue by yehorsyrin** [lmmfranco/nintendo-switch-eshop#622]
Hello.
I am getting 404 while opening any object in the documentation.
F.e. https://lmmfranco.github.io/nintendo-switch-eshop/interfaces/GameUS.html
![image](https://user-images.githubusercontent.com/23188336/140411084-01d9244c-99a1-4046-92d0-9fd9ddb2e3c0.png)

**Comment by Favna** [comment]
Oh gosh darn it, I think I know why this is happening. Thanks for the report, I'll look into it asap. Will probably be tomorrow-ish (Friday).

**Comment by Favna** [comment]
This has been fixed, though the URL has changed as I have changed how the documentation is deployed. The fixed URL is https://lmmfranco.github.io/nintendo-switch-eshop/docs/Documentation/interfaces/GameUS
