### ISSUE TITLE
DLCs

### ISSUE THREAD

**Issue by CyberMew** [lmmfranco/nintendo-switch-eshop#7]
Will it be supported?

**Comment by lmmfranco** [comment]
@CyberMew I didn't have time to work on this package for some months now. I'm still not sure if Nintendo API's expose DLC data or not, as soon as I can I'll look into that.
For the time being, any information about the topic is welcome.

**Comment by Favna** [comment]
DLCs are not exposed by the Nintendo API for as far as I know so I'm closing this issue.
