### ISSUE TITLE
Is the pagination work ?

### ISSUE THREAD

**Issue by grass0916** [lmmfranco/nintendo-switch-eshop#8]
`GAME_LIST_LIMIT` is assigned `200` [ref](https://github.com/lmmfranco/nintendo-switch-eshop/blob/master/index.js#L15)

`GAME_LIST_LIMIT` is used in `getGamesAmerica()` [ref](https://github.com/lmmfranco/nintendo-switch-eshop/blob/master/index.js#L179)

## My test case

```js
const SwitchEshop = require('nintendo-switch-eshop');
const us = SwitchEshop.getGamesAmerica();
us.then(data => console.log(data.length));
```

## Test case output (25 JAN 2018)

```
433
```

**Comment by lmmfranco** [comment]
Sorry if the docs weren't clear enough. Let me explain.
Under the hood the method is paginating, but it accumulates results until all data is fetched.
My intent by saying "paginates every 200 games" on the docs was to make sure people are aware that there may be more than one outgoing HTTP request.

If control over pagination is something that can be of help I may implement it when I have time to. ( A pull request is also welcome )

**Comment by grass0916** [comment]
Dear @lmmfranco ,

Thanks for your explain. I had understood you recursively request via API [here](https://github.com/lmmfranco/nintendo-switch-eshop/blob/master/index.js#L191).

**Comment by lmmfranco** [comment]
@grass0916 I have also added a `limit` option to the requests in 1.1.0
