### ISSUE TITLE
[BUG] parseNSUID returns null for GameJP objects and their properties are not arrays

### ISSUE THREAD

**Issue by SquidEpps** [lmmfranco/nintendo-switch-eshop#90]
**Please describe the problem you are having in as much detail as possible:**

For Japanese games `parseNSUID` [extracts nsuid from the first element of `LinkURL` property with a regex ](https://github.com/lmmfranco/nintendo-switch-eshop/blob/0f6c2426412a2aa2788e1be9354e3f0209ce6e6f/src/nintendo-switch-eshop.ts#L480). However this property is actually a string and not an array. So regex tests not the whole link, but the first letter of it, does not match and the function returns null.

Further investigation showed, that all other properties of GameJP are not arrays, contrary to what documentations says.

This might look like an API issue but I don't know how did the Japanese eShop API look like before so I can't say for sure. I personally think that it could be an issue with the XML parser (version changed and introduced breaking changes?), did not dive deep into this though.

**Include a reproducible code sample here, if possible:**
```js

// Not 100% reproducible as it depends on the external API
// but should be good enough to illustrate this issue

const { getGamesJapan, parseNSUID, Region } = require('nintendo-switch-eshop');

getGamesJapan()
  .then(games => {
    for (const game of games) {
      if (/\d{14}$/.test(game.LinkURL)) {
        console.log(game.LinkURL, parseNSUID(game, Region.ASIA))
        break;
      }
    }
  });

```

**Output:**

`LinkURL` is a string, `parseNSUID` returned null

```
https://ec.nintendo.com/JP/ja/titles/70010000002204 null
```

**Expected output:**

`LinkURL` is a single item array, `parseNSUID` parses correctly

```
[ 'https://ec.nintendo.com/JP/ja/titles/70010000002204' ] null
```

**Further details:**
- version: 2.2.5
- Node.js version: 12.13.0
- Operating system: openSUSE Tumbleweed 20191124
- Priority this issue should have – please be realistic and elaborate if possible: High, as the function does not work, as expected, and game object structure differs from what is described in the documentation

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Favna** [comment]
Reproduced and fixed. The LinkURL, along with other properties for that matter, are no longer given back as array from the XML parser.

By the way you don't have to write the regex yourself, just import `JP_NSUID_REGEX` as seen below:

![image](https://user-images.githubusercontent.com/4019718/69751259-014af680-114f-11ea-9f3b-13246b5129fb.png)

**Comment by Favna** [comment]
Version 2.2.6 has been published to NPM
