### ISSUE TITLE
[BUG] Package requires tslib which is not on dependencies list

### ISSUE THREAD

**Issue by SquidEpps** [lmmfranco/nintendo-switch-eshop#91]
**Please describe the problem you are having in as much detail as possible:**

The package requires `tslib` to run (`dist/index.js`, line 3), but it is not listed in the dependencies section of `package.json`. So it is not installed and `require('nintendo-switch-eshop')` throws an error.

`tslib` is included in built js file due to `importHelpers` option of `tsconfig.json` which is enabled not directly in this project, but in [another one](https://github.com/favware/node-packages/blob/4f70c797a573fa3b3d8d05227ee671a1b2228478/packages/ts-config/tsconfig.json#L19) through the [`extends` option](https://github.com/lmmfranco/nintendo-switch-eshop/blob/0f6c2426412a2aa2788e1be9354e3f0209ce6e6f/tsconfig.json#L2).

Either `importHelpers` should be disabled or `tslib` should be listed as a dependency.

**Include a reproducible code sample here, if possible:**

_Requires clean environment without typescript installed globally_

```sh
$ npm install nintendo-switch-eshop
$ node -r nintendo-switch-eshop -e ''
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'tslib'
Require stack:
- /tmp/test/node_modules/nintendo-switch-eshop/dist/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/test/node_modules/nintendo-switch-eshop/dist/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/test/node_modules/nintendo-switch-eshop/dist/index.js',
    'internal/preload'
  ]
}


```

**Further details:**
- version: 2.2.5
- Node.js version: 12.13.0
- Operating system: openSUSE Tumbleweed 20191124
- Priority this issue should have – please be realistic and elaborate if possible: High, package not usable in clean environments, eg. docker container

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Favna** [comment]
ah.... yeah.... Oversight. So used to TypeScript development environments where it's always present. I never code in JS anymore.

**Comment by Favna** [comment]
Version 2.2.6 has been published to NPM
