### ISSUE TITLE
[QUESTION] Offset not working on getGamesAmerica

### ISSUE THREAD

**Issue by reinvanimschoot** [lmmfranco/nintendo-switch-eshop#93]
I was trying out the latest version of the package.

When I just do 

```
async function getAmericanGames() {
  const result = await getGamesAmerica();

  console.log(result.length)
}

getAmericanGames();
```

The resulting amount of games returned is 972. This is a bit confusing since this is not the entire collection of US Switch eShop games but the documentation states that if you don't pass in any options to the function, you get the entire collection.

`On the US eshop, the max limit is 100. Leave empty to get all the games.`

`Promise containing all the games`

So I tried adding an offset:

```
async function getAmericanGames() {
  const result = await getGamesAmerica({}, 900);

  console.log(result.length)
}

getAmericanGames();
```
And I got the exact same result back. 972 games. 

I tried using any offset from 1000 to 10000 but the result is always the same.

Am I doing something wrong? How can I reliably get the entire list of US eShop games?

**Comment by Favna** [comment]
This is because by default the lib will filter for games that are on nintendo.com, therefore only digital versions. If you want to get all games use `getGamesAmerica({shop: 'unfiltered'})` which should return at least 1500 results as per the test written for it:

```ts
  test('should allow unfiltered shop', async () => {
    jest.setTimeout(60000);
    const data = await getGamesAmerica({shop: 'unfiltered'});
    expect(data).toBeInstanceOf(Object);
    expect(data.length).toBeGreaterThanOrEqual(1500);
  });
```
