### ISSUE TITLE
[API]  game_code in US region data is not found

### ISSUE THREAD

**Issue by ineo6** [lmmfranco/nintendo-switch-eshop#99]
**Please describe the problem you are having in as much detail as possible:**

Can not find game_code in us region data.

![image](https://user-images.githubusercontent.com/3783838/71141673-e51f0e80-224f-11ea-9b1f-4441e2df4125.png)

**Further details:**
- version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Favna** [comment]
I noticed this as well but I'm afraid there's not much we can do about it. We get all fields from the API so if it's not there then they removed it on the API. 

I was considering throwing a deprecation warning for parseGameCode but in a (probably futile) hope I thought maybe it would return eventually.

**Comment by Favna** [comment]
Properly deprecated in v2.2.8. The function now throws a DeprecationWarning using the warning event, which will be printed in stderr. The function will return an empty string whenever no game_code is present, or return the proper game_code if the API decides to include it again. game_code has been marked as potentially undefined in the TypeScript typings.
